version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - DP_KEYS_PATH=/root/.aspnet/DataProtection-Keys
      - DP_CERT_PATH=/app/secrets/dp_key.pfx # optional, mount if you want certificate protection
      - DB_MIGRATE_RETRIES=10
      - DB_MIGRATE_DELAY_MS=3000
      - ASPNETCORE_URLS=http://+:5000
    volumes:
      - ./data/dataprotection-keys:/root/.aspnet/DataProtection-Keys
      - ./secrets/dp_key.pfx:/app/secrets/dp_key.pfx:ro # optional
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  redis-ui:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
