version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__Redis=redis:6379
      - AUTO_MIGRATE=true  # enable EF automatic migrations for dev (SQL Server)
    volumes:
      - ./data/dataprotection-keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - redis

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always

  redis-ui:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
